const chainsSupported = [
  {
    chain: 'akash',
    name: 'Akash',
    baseChain: 'CosmosChain',
    chainId: 'akashnet-2',
    contract: '',
  },
  {
    chain: 'arbitrum',
    name: 'Arbitrum',
    baseChain: 'EVM',
    contract: '0xB50721BCf8d664c30412Cfbc6cf7a15145234ad1'
  },
  {
    chain: 'aurora',
    name: 'Aurora',
    baseChain: 'EVM',
    constract: '0xAaAAAA20D9E0e2461697782ef11675f668207961',
  },
  {
    chain: 'avalanche',
    name: 'Avalanche',
    baseChain: 'EVM',
    contract: '0x93567d6B6553bDe2b652FB7F197a229b93813D3f',
  },
  {
    chain: 'axelar',
    name: 'Axelar',
    baseChain: 'CosmosChain',
    chainId: 'axelar-dojo-1',
    contract: '',
  },
  {
    chain: 'binance',
    name: 'Binance',
    contract: '',
  },
  {
    chain: 'binanceSmartChain',
    name: 'Binance Smart Chain',
    baseChain: 'EVM',
    contract: '0x0b95993a39a363d99280ac950f5e4536ab5c5566',
  },
  {
    chain: 'bitcoin',
    name: 'Bitcoin',
    contract: '',
  },
  {
    chain: 'bitcoincash',
    name: 'Bitcoin Cash',
    contract: '',
  },
  {
    chain: 'cantoEVM',
    name: 'Canto',
    baseChain: 'EVM',
    contract: '0x4e71A2E537B7f9D9413D3991D37958c0b5e1e503',
  },
  {
    chain: 'cosmos',
    name: 'Cosmos Hub',
    baseChain: 'CosmosChain',
    chainId: 'cosmoshub-4',
    contract: '',
  },
  {
    chain: 'crescent',
    name: 'Crescent',
    baseChain: 'CosmosChain',
    chainId: 'crescent-1',
    contract: '',
  },
  {
    chain: 'cronosEVM',
    name: 'Cronos',
    baseChain: 'EVM',
    contract: '0xddf993bebbd397f2a42de7c39f09f9c8e34ef322',
  },
  {
    chain: 'dogecoin',
    name: 'Dogecoin',
    contract: '',
  },
  {
    chain: 'ethereum',
    name: 'Ethereum',
    baseChain: 'EVM',
    contract: '0xad6d458402f60fd3bd25163575031acdce07538d',
  },
  {
    chain: 'fantom',
    name: 'Fantom',
    baseChain: 'EVM',
    contract: '0xcc2cdacec2e8bccd3b3201e744bdf51628d00184b7cb420f41e25ee0d6853',
  },
  {
    chain: 'juno',
    name: 'Juno',
    baseChain: 'CosmosChain',
    chainId: 'juno-1',
    contract: '',
  },
  {
    chain: 'kava',
    name: 'Kava',
    baseChain: 'CosmosChain',
    chainId: 'kava_2222-10',
    contract: '',
  },
  {
    chain: 'kujira',
    name: 'Kujira',
    baseChain: 'CosmosChain',
    chainId: 'kaiyo-1',
    contract: '',
  },
  {
    chain: 'litecoin',
    name: 'Litecoin',
    contract: '',
  },
  {
    chain: 'mayachain',
    name: 'Maya Protocol',
    contract: '',
  },
  {
    chain: 'mars',
    name: 'Mars',
    baseChain: 'CosmosChain',
    chainId: 'mars-1',
    contract: '',
  },
  {
    chain: 'near',
    name: 'NEAR',
    baseChain: 'NEAR',
    contract: '',
  },
  {
    chain: 'optimism',
    name: 'Optimism',
    baseChain: 'EVM',
    contract: '0x7cade2beb25ede5f8590602b1b24c4f610fde605',
  },
  {
    chain: 'osmosis',
    name: 'Osmosis',
    baseChain: 'CosmosChain',
    chainId: 'osmosis-1',
    contract: '',
  },
  {
    chain: 'polygon',
    name: 'Polygon',
    baseChain: 'EVM',
    contract: '0x455e53CBB86018Ac2B8092FdCd39d8444aFFC3F6',
  },
  {
    chain: 'solana',
    name: 'Solana',
    baseChain: 'Solana',
    contract: '',
  },
  {
    chain: 'stargaze',
    name: 'Stargaze',
    baseChain: 'CosmosChain',
    chainId: 'stargaze-1',
    contract: '',
  },
  {
    chain: 'stride',
    name: 'Stride',
    baseChain: 'CosmosChain',
    chainId: 'stride-1',
    contract: '',
  },
  {
    chain: 'terra',
    name: 'Terra',
    baseChain: 'Terra',
    contract: '',
  },
  {
    chain: 'thorchain',
    name: 'THORChain',
    contract: '',
  },
];

export default chainsSupported;
