const chainsSupported = [
  {
    chain: 'akash',
    name: 'Akash',
    baseChain: 'CosmosChain',
    chainId: 'akashnet-2',
    contract: '',
  },
  {
    chain: 'arbitrum',
    name: 'Arbitrum',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'aurora',
    name: 'Aurora',
    baseChain: 'EVM',
    constract: '',
  },
  {
    chain: 'avalanche',
    name: 'Avalanche',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'axelar',
    name: 'Axelar',
    baseChain: 'CosmosChain',
    chainId: 'axelar-dojo-1',
    contract: '',
  },
  {
    chain: 'binance',
    name: 'Binance',
    contract: '',
  },
  {
    chain: 'binanceSmartChain',
    name: 'Binance Smart Chain',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'bitcoin',
    name: 'Bitcoin',
    contract: '',
  },
  {
    chain: 'bitcoincash',
    name: 'Bitcoin Cash',
    contract: '',
  },
  {
    chain: 'cantoEVM',
    name: 'Canto',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'cosmos',
    name: 'Cosmos Hub',
    baseChain: 'CosmosChain',
    chainId: 'cosmoshub-4',
    contract: '',
  },
  {
    chain: 'crescent',
    name: 'Crescent',
    baseChain: 'CosmosChain',
    chainId: 'crescent-1',
    contract: '',
  },
  {
    chain: 'cronosEVM',
    name: 'Cronos',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'dogecoin',
    name: 'Dogecoin',
    contract: '',
  },
  {
    chain: 'ethereum',
    name: 'Ethereum',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'fantom',
    name: 'Fantom',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'juno',
    name: 'Juno',
    baseChain: 'CosmosChain',
    chainId: 'juno-1',
    contract: '',
  },
  {
    chain: 'kava',
    name: 'Kava',
    baseChain: 'CosmosChain',
    chainId: 'kava_2222-10',
    contract: '',
  },
  {
    chain: 'kujira',
    name: 'Kujira',
    baseChain: 'CosmosChain',
    chainId: 'kaiyo-1',
    contract: '',
  },
  {
    chain: 'litecoin',
    name: 'Litecoin',
    contract: '',
  },
  {
    chain: 'mayachain',
    name: 'Maya Protocol',
    contract: '',
  },
  {
    chain: 'mars',
    name: 'Mars',
    baseChain: 'CosmosChain',
    chainId: 'mars-1',
    contract: '',
  },
  {
    chain: 'near',
    name: 'NEAR',
    baseChain: 'NEAR',
    contract: '',
  },
  {
    chain: 'optimism',
    name: 'Optimism',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'osmosis',
    name: 'Osmosis',
    baseChain: 'CosmosChain',
    chainId: 'osmosis-1',
    contract: '',
  },
  {
    chain: 'polygon',
    name: 'Polygon',
    baseChain: 'EVM',
    contract: '',
  },
  {
    chain: 'solana',
    name: 'Solana',
    baseChain: 'Solana',
    contract: '',
  },
  {
    chain: 'stargaze',
    name: 'Stargaze',
    baseChain: 'CosmosChain',
    chainId: 'stargaze-1',
    contract: '',
  },
  {
    chain: 'stride',
    name: 'Stride',
    baseChain: 'CosmosChain',
    chainId: 'stride-1',
    contract: '',
  },
  {
    chain: 'terra',
    name: 'Terra',
    baseChain: 'Terra',
    contract: '',
  },
  {
    chain: 'thorchain',
    name: 'THORChain',
    contract: '',
  },
];

export default chainsSupported;
